### ISSUE TITLE
Inventory issue

### ISSUE THREAD

**Issue by KeiFeeD** [AndrewHack242/Ordered_Custom_Boombox#2] opened 2024-11-22 21:10 UTC
When I take item it doubles in inventory. And if I drop that item it's copy will be stay inventory, but item will not be in arms

**Comment by AndrewHack242** [comment] 2024-11-23 00:55
Can you elaborate a bit? does this happen when picking up an item while holding the boombox? and how does this 'copy' work? does it go in a different slot than the 'real' one?

Does this happen any time you attempt to pick up an item?

**Comment by AndrewHack242** [comment] 2024-11-23 01:05
And if you were using other mods, can you send me a modpack code or link?

**Comment by AndrewHack242** [comment] 2024-12-03 01:39
Closing due to inability to reproduce

**Closed as not planned by AndrewHack242** 2024-12-03 01:39 UTC
